name: mlops_exam
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - libffi=3.4.2=hd77b12b_6
  - openssl=1.1.1s=h2bbff1b_0
  - pip=22.3.1=py310haa95532_0
  - python=3.10.8=h966fe2a_1
  - python_abi=3.10=2_cp310
  - sentencepiece=0.1.96=py310h476a331_1
  - sqlite=3.40.0=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.8=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - aiohttp==3.8.3
    - aiohttp-retry==2.8.3
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - amqp==5.1.1
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asyncssh==2.13.0
    - atpublic==3.1.1
    - attrs==22.2.0
    - babel==2.11.0
    - billiard==3.6.4.0
    - cachetools==5.2.1
    - celery==5.2.7
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - colorama==0.4.6
    - commonmark==0.9.1
    - configobj==5.0.6
    - coverage==7.0.5
    - cryptography==39.0.0
    - datasets==2.8.0
    - dictdiffer==0.9.0
    - dill==0.3.6
    - diskcache==5.4.0
    - distro==1.8.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.19
    - dpath==2.1.4
    - dulwich==0.20.50
    - dvc==2.41.1
    - dvc-data==0.29.0
    - dvc-gdrive==2.19.1
    - dvc-http==2.30.0
    - dvc-objects==0.14.1
    - dvc-render==0.0.17
    - dvc-studio-client==0.3.0
    - dvc-task==0.1.9
    - dvclive==1.3.2
    - exceptiongroup==1.1.0
    - fastapi==0.89.1
    - filelock==3.9.0
    - flake8==6.0.0
    - flatten-dict==0.4.2
    - flufl-lock==7.1.1
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - funcy==1.17
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-api-core==2.11.0
    - google-api-python-client==2.72.0
    - google-auth==2.16.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.58.0
    - grandalf==0.6
    - h11==0.14.0
    - httpcore==0.16.3
    - httplib2==0.21.0
    - httpx==0.23.3
    - huggingface-hub==0.11.1
    - hydra-core==1.3.1
    - idna==3.4
    - imagesize==1.4.1
    - iniconfig==2.0.0
    - iterative-telemetry==0.0.6
    - jinja2==3.1.2
    - kombu==5.2.4
    - lightning-utilities==0.5.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mccabe==0.7.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - mypy==0.991
    - mypy-extensions==0.4.3
    - nanotime==0.5.2
    - networkx==3.0
    - numpy==1.24.1
    - oauth2client==4.1.3
    - omegaconf==2.3.0
    - packaging==22.0
    - pandas==1.5.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pipreqs==0.4.11
    - pluggy==1.0.0
    - promise==2.3
    - prompt-toolkit==3.0.36
    - protobuf==3.19.5
    - psutil==5.9.4
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.10.0
    - pycparser==2.21
    - pydantic==1.10.4
    - pydot==1.4.2
    - pydrive2==1.15.0
    - pyflakes==3.0.1
    - pygit2==1.11.1
    - pygments==2.14.0
    - pygtrie==2.5.0
    - pyopenssl==23.0.0
    - pyparsing==3.0.9
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - pytorch-lightning==1.8.6
    - pytz==2022.7
    - pywin32==305
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - rich==13.0.1
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - scmrepo==0.1.5
    - sentry-sdk==1.13.0
    - setproctitle==1.3.2
    - setuptools==65.6.3
    - shortuuid==1.0.11
    - shtab==1.5.8
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.3
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - starlette==0.22.0
    - tabulate==0.9.0
    - tensorboardx==2.5.1
    - tokenizers==0.13.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - torch==1.13.1
    - torchmetrics==0.11.0
    - tqdm==4.64.1
    - transformers==4.25.1
    - typing-extensions==4.4.0
    - uritemplate==4.1.1
    - urllib3==1.26.13
    - vine==5.0.0
    - voluptuous==0.13.1
    - wandb==0.13.7
    - wcwidth==0.2.5
    - xxhash==3.2.0
    - yarg==0.1.9
    - yarl==1.8.2
    - zc-lockfile==2.0
prefix: C:\Users\mikke\anaconda3\envs\mlops_exam
